version: '3.8'

services:
  eureka:
    container_name: javame-eureka-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10280:10280"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - local-net

networks:
  local-net:
    external: true
