spring:
  application:
    name: eureka-server
    ## local 테스트용 설정. 배포시 profiles부터 local 까지 주석 처리 바람
  profiles:
    active: local

server:
  port: 10280
  shutdown: graceful

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: INFO
    org.springframework: INFO
